### ISSUE TITLE
Indentation for "Examples"

### ISSUE THREAD

**Issue by R0boC0p** [drweb86/Gherkin-Beautifier-VS-Code-Plugin#14]
Hi, could you fix the indentation for Examples table in the .feature file. It always uses 0, although set to 2 tabs.

Thanks a lot and great work!
Cheers Rob

```
Scenario Outline: Setting can be searched for
	When '<Search Text>' is entered into the search bar
	Then the Analog Output setting is displayed in the filtered setting groups
		
	Examples:
		| Search Text    |
		| Chart Output 1 |
		| Chart Output 2 |
		| Analog Output  |
```

**Comment by drweb86** [comment]
Hi @r0bDaMob ,

Let me check!

**Comment by drweb86** [comment]
Seems like it uses spacing before Scenario setting to create spacing before Examples!

**Comment by drweb86** [comment]
It will be fixed in the version 6. Please reopen if won't work

**Comment by R0boC0p** [comment]
thanks a very lot for your support!!
