### ISSUE TITLE
Incorrect table autoformat with comments

### ISSUE THREAD

**Issue by k03mad** [drweb86/Gherkin-Beautifier-VS-Code-Plugin#22]
Hello,

Is there a way to support comments in the tables?
Example table:

```
    Scenario Outline: test
        Given "<PAGE>" opened
        Then I enter the "<TEXT>"

        Examples:
            | PAGE        | TEXT           |
            # some comment about this example
            | /search?a=b | hello          |
            # next comment about current example
            | /query      | test test test |
```

Autoformat removes table indents:

```
    Scenario Outline: test
        Given "<PAGE>" opened
        Then I enter the "<TEXT>"

        Examples:
            | PAGE | TEXT |
            # some comment about example
            | /search?a=b | hello |
            # another comment about next example
            | /query | test test test |
```

**Comment by drweb86** [comment]
Hi, Kirill,

Consider adding a New column to a table called Comments or Description and
put there your comment as table cell. Will it solve issue you are facing
with?

Let me know if this works for you

пн, 21 июн. 2021 г., 14:04 Kirill Molchanov ***@***.***>:

**Comment by k03mad** [comment]
Yep, it certainly work as a separate column

Сomments between lines are most likely a very rare case
Just thought that this could be supported :)

**Comment by drweb86** [comment]
Nice, i've checked cucumberjs parser and found that they are supported for
tables there too. But i really have not much time to rewrite plugin using
their parser or change my table recognizer. So lets close it until there
will be more ppl facing same issue.

пн, 21 июн. 2021 г., 15:16 Kirill Molchanov ***@***.***>:
