### ISSUE TITLE
Can you add support to Gherkin Dialects (Italian, spanish etc)?

### ISSUE THREAD

**Issue by bistick** [drweb86/Gherkin-Beautifier-VS-Code-Plugin#7]
Can you add support to Gherkin Dialects (Italian, spanish etc)?

**Comment by drweb86** [comment]
Hi @bistick 

Sure. Seems like i can take translations from there
https://cucumber.io/docs/gherkin/reference/#overview

**Comment by drweb86** [comment]
Will be released with version #5
